module.exports = {
  'accessor-pairs': 'off',
  'arrow-body-style': ['error', 'as-needed', {
    'requireReturnForObjectLiteral': false,
  }],
  'block-scoped-var': 'error',
  'camelcase': ['error', {
    'properties': 'never',
  }],
  'capitalized-comments': 'off',
  'class-methods-use-this': 'off',
  'complexity': 'off',
  'consistent-return': 'off',
  'consistent-this': 'off',
  'curly': 'off',
  'default-case': 'off',
  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-notation': 'error',
  'eqeqeq': 'error',
  'func-name-matching': ['error', {
    'considerPropertyDescriptor': true,
    'includeCommonJSModuleExports': false,
  }],
  'func-names': 'off',
  'func-style': 'off',
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'off',
  'id-denylist': 'off',
  'id-length': 'off',
  'id-match': 'off',
  'init-declarations': 'off',
  'logical-assignment-operators': ['off', 'always', {
    'enforceForIfStatements': true,
  }],
  'max-classes-per-file': 'off',
  'max-depth': 'off',
  'max-lines': 'off',
  'max-lines-per-function': 'off',
  'max-nested-callbacks': 'off',
  'max-params': 'off',
  'max-statements': 'off',
  'multiline-comment-style': 'off',
  'new-cap': ['error', {
    'newIsCap': true,
  }],
  'no-alert': 'off',
  'no-array-constructor': 'error',
  'no-bitwise': 'off',
  'no-caller': 'off',
  'no-case-declarations': 'error',
  'no-confusing-arrow': ['error', {
    'allowParens': true,
  }],
  'no-console': 'off',
  'no-delete-var': 'error',
  'no-div-regex': 'off',
  'no-else-return': 'error',
  'no-empty': ['error', {
    'allowEmptyCatch': true,
  }],
  'no-empty-function': ['error', {
    'allow': [
      'arrowFunctions',
      'functions',
      'methods',
    ],
  }],
  'no-eq-null': 'off',
  'no-eval': 'warn',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-label': 'error',
  'no-extra-semi': 'error',
  'no-floating-decimal': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': 'off',
  'no-implicit-globals': 'off',
  'no-implied-eval': 'warn',
  'no-inline-comments': 'off',
  'no-invalid-this': 'off',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': ['error', {
    'allowLoop': false,
    'allowSwitch': false,
  }],
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'error',
  'no-magic-numbers': 'off',
  'no-mixed-operators': 'error',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'off',
  'no-nested-ternary': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-object': 'error',
  'no-new-wrappers': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-octal': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': 'off',
  'no-plusplus': 'off',
  'no-proto': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-restricted-exports': ['error', {
    'restrictedNamedExports': [
      'default',
      'then',
    ],
  }],
  'no-restricted-globals': 'error',
  'no-restricted-imports': 'off',
  'no-restricted-properties': 'error',
  'no-restricted-syntax': 'error',
  'no-return-assign': 'off',
  'no-return-await': 'error',
  'no-script-url': 'error',
  'no-sequences': 'error',
  'no-shadow': 'off',
  'no-shadow-restricted-names': 'error',
  'no-ternary': 'off',
  'no-throw-literal': 'error',
  'no-undef-init': 'error',
  'no-undefined': 'off',
  'no-underscore-dangle': ['error', {
    'allowAfterThis': false,
    'allowAfterSuper': false,
    'enforceInMethodNames': true,
  }],
  'no-unneeded-ternary': 'error',
  'no-unused-expressions': 'error',
  'no-unused-labels': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'off',
  'no-useless-escape': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': 'off',
  'no-warning-comments': 'off',
  'no-with': 'error',
  'object-shorthand': 'error',
  'one-var': ['error', 'never'],
  'one-var-declaration-per-line': 'error',
  'operator-assignment': 'error',
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-destructuring': 'error',
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'off',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'off',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'quote-props': 'off',
  'radix': 'error',
  'require-await': 'error',
  'require-unicode-regexp': 'off',
  'require-yield': 'error',
  'sort-imports': ['off', {
    'memberSyntaxSortOrder': ['none', 'all', 'mutiple', 'single'],
  }],
  'sort-keys': 'off',
  'sort-vars': 'off',
  'spaced-comment': 'warn',
  'strict': ['error', 'never'],
  'symbol-description': 'error',
  'vars-on-top': 'error',
  'yoda': 'error',
};
